server:
  port: 8802
spring:
  application:
    name: cloud-provider-user
eureka:
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://lxl:123456@localhost:8761/eureka/,http://lxl:123456@localhost:8762/eureka/,http://lxl:123456@localhost:8763/eureka/      #服务注册中信地址，含有BASIC认证的用户名和密码

  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}